import { NextRequest, NextResponse } from 'next/server'
import Fuse from 'fuse.js'

const glossary = [
  { term: "retribuzione diretta", explanation: "LA RETRIBUZIONE DIRETTA  È quella relativa all’effettiva prestazione del lavoratore ed è stabilita dal contratto collettivo individuata normalmente su base mensile:\n1. Paga Base\n2. La Contingenza\n3. Elemento Distinto dalla Retribuzione (eventuale)\n4. Scatti d’anzianità\n5. Altri elementi" },
  { term: "retribuzione indiretta", explanation: "Si tratta della retribuzione dovuta al lavoratore, al verificarsi di determinati eventi, indipendentemente dalla esecuzione della prestazione lavorativa, ad esempio:Malattia\nMaternità\nInfortunio\nFerie\nFestività" },
  { term: "retribuzione differita", explanation: "Sono gli emolumenti che pur maturando nel tempo, nel corso del rapporto di lavoro, sono erogati in particolari momenti: Trattamento di Fine Rapporto, Trattenuta per Fondo Pensione,13a o 14a Mensilità" },
  { term: "retribuzione lorda", explanation: "La retribuzione stabilita dai contratti collettivi applicati in azienda è\nconsiderata al “lordo”; vale a dire, che su queste somme debbono essere\neffettuate le trattenute previdenziali e fiscali.\n\nIl lavoratore è tenuto a pagare i contributi previdenziali e le ritenute fiscali.I contributi sono somme che il lavoratore e il datore versano per la previdenza sociale..." },
  { term: "assegni nucleo familiare", explanation: "L’assegno spetta:\n• Durante il Rapporto di Lavoro\n• In Disoccupazione\n• In Cassa Integrazione Guadagni\n• In Mobilità\n• In Malattia o maternità\n• In Congedo Matrimoniale\n• Ai Pensionati"},
  { term: "trattamento di fine rapporto t.f.r." , explanation: "Il trattamento di fine rapporto è un elemento della retribuzione il cui pagamento viene differito ad un momento successivo rispetto a quello di prestazione dell’attività lavorativa.\n\nTale trattamento si calcola accantonando, al termine di ciascun anno di servizio, un quota pari, e comunque non superiore, all’importo delle retribuzione dovuta per l’anno stesso, diviso 13,5. A decorrere dal 1° gennaio 2007 i lavoratori sono chiamati a decidere se destinare il proprio TFR da maturare alle forme pensionistiche complementari o mantenere lo stesso presso il datore di lavoro."},
  { term: "retribuzione netta" , explanation: "Dalla retribuzione lorda si passa alla retribuzione netta sottraendo le ritenute sociali e fiscali. Si calcola nel seguente modo:\nRETRIBUZIONE LORDA(R.L.) - CONTRIBUTI PREVIDENZIALI (normalmente 9,19% di R.L.) = IMPONIBILE FISCALE\nIMPONIBILE FISCALE - TRATTENUTE IRPEF AL NETTO DELLE DETRAZIONI FISCALI = SALARIO NETTO DA TRATTENUTE\nSALARIO NETTO DA TRATTENUTE+ ASSEGNO NUCLEO FAMILIARE= SALARIO NETTO PERCEPITO IN BUSTA PAGA"},
  { term: "periodo di paga" , explanation: "di norma la retribuzione deve essere corrisposta entro la fine del mese di paga;\n• in ogni caso i contratti possono prevedere anche scadenze diverse: soprattutto nei confronti del personale retribuito a ore, in considerazione della necessità di conoscere prima le ore lavorate e poter calcolare la retribuzione spettante."},
  { term: "dati anagrafici" , explanation: "I dati anagrafici, in Italia, sono le informazioni personali di un individuo, quali nome, cognome, data e luogo di nascita, sesso, codice fiscale, indirizzo di residenza, dati relativi allo stato civile, famiglia anagrafica e altro. Questi dati vengono conservati presso gli uffici anagrafici dei comuni.Più nello specifico, i dati anagrafici includono:\nNome e Cognome:\nData e luogo di nascita:\nCodice fiscale:\nIndirizzo di residenza:\nStato civile (single, sposato, divorziato, ecc.):\nDati relativi alla famiglia anagrafica (se applicabile):\nAltri dati: come eventuali variazioni di residenza, informazioni sulla cittadinanza, ecc. "},
  { term: "competenze" , explanation: "Le competenze in busta paga rappresentano la somma totale degli emolumenti dovuti al dipendente per il lavoro svolto. Questo include non solo lo stipendio base, ma anche indennità, straordinari, premi, ferie non godute e altri importi previsti. In sostanza, le competenze sono la parte \"lorda\" della retribuzione, prima delle trattenute fiscali e previdenziali. \n\nEcco alcuni esempi di voci che possono rientrare nelle competenze:\nRetribuzione base o minimo tabellare: Lo stipendio fondamentale previsto dal contratto collettivo nazionale.\n\n\nIndennità di contingenza: Un importo variabile che tiene conto del costo della vita. \nElemento distinto della retribuzione (EDR): Un importo aggiuntivo introdotto da contratti collettivi. \nTerzo elemento: Un'altra indennità integrativa della retribuzione. \nScatti di anzianità: Aumenti retributivi per la durata della carriera lavorativa. \nAssegni ad personam: Aumenti retributivi personali. \nRetribuzione di merito: Aumenti legati alla performance lavorativa. \nLavoro straordinario: Ore lavorate oltre l'orario normale, con maggiorazioni. \nFerie e permessi non goduti: Risarcimento per giorni di riposo non utilizzati. \nPremi di risultato: Incentivi economici legati a obiettivi aziendali. \nIndennità di trasferta: Importi per coprire le spese sostenute durante viaggi di lavoro. \nEventuali indennità di trasferta, di missione, di rappresentanza, di vitto, di alloggio o di altri tipi. Inoltre, in alcune situazioni, le competenze possono includere anche voci di natura sociale, come l'integrazione di indennità a carico INPS o INAIL. Le competenze, insieme alle trattenute (fiscali, previdenziali, etc.), determinano lo stipendio netto che il dipendente riceve."},
  { term: "trattenute" , explanation: "Le trattenute in busta paga, detratte dallo stipendio lordo, comprendono diverse voci, tra cui contributi INPS, IRPEF, addizionali regionali e comunali, e possono includere anche trattenute sindacali. Queste trattenute servono a coprire i diversi obblighi fiscali e previdenziali del lavoratore, e il loro importo varia in base al reddito e alle eventuali detrazioni fiscali. "},
  { term: "presenze assenze" , explanation: "un calendario delle presenze, da cui risulti, per ogni giorno, il numero di ore di lavoro e di assenze effettuate da ciascun lavoratore. "},
  { term: "festività" , explanation: "Le festività sono pagate in busta paga e vengono considerate come giorni lavorativi retribuiti, anche se il lavoratore non presta servizio. In particolare, le festività nazionali e le feste infrasettimanali, comprese quelle del Santo Patrono del luogo, sono retribuite al 100%. Se il lavoratore presta servizio in una giornata festiva, ha diritto a una maggiorazione retributiva."},
  { term: "riposi" , explanation: "I riposi nella busta paga si riferiscono a diversi tipi di permessi e assenze che un lavoratore può godere, come riposo settimanale, festività, permessi retribuiti (o ROL) e recupero compensativo. Tali riposi possono essere indicati nella busta paga come ore di permesso o giorni di assenza, e possono influenzare la retribuzione del lavoratore. "},
  { term: "malattia" , explanation: "In Italia, in caso di malattia, la busta paga viene modificata per riflettere l'indennità di malattia, che è una parte della retribuzione pagata dall'INPS. Generalmente, i primi 3 giorni di malattia non vengono indennizzati, ma il datore di lavoro potrebbe integrarla. L'indennità INPS varia a seconda del periodo di malattia (50% per i primi 20 giorni, 66,66% dopo) e può essere integrata dal datore di lavoro. \nCome funziona la malattia in busta paga:\nI primi 3 giorni:\nIn genere, non sono indennizzati dall'INPS, ma il datore di lavoro può integrarle secondo i contratti collettivi. \n\nDal 4° al 20° giorno:\nL'INPS paga l'indennità pari al 50% della retribuzione giornaliera media. \nDal 21° giorno in poi:\nL'INPS paga l'indennità pari al 66,66% della retribuzione giornaliera media.\n L'indennità viene pagata al lavoratore tramite la busta paga. Il datore di lavoro anticipa la retribuzione e l'INPS rimborsa una parte. \nChi paga la malattia:\n\nIl datore di lavoro: Paga la retribuzione al lavoratore durante il periodo di malattia.\nL'INPS: Paga l'indennità di malattia al datore di lavoro (che poi la rimborsa al dipendente). \n\nImportante: La durata massima dell'indennità di malattia è di 180 giorni nell'anno sola"},
  { term: "contributo ente bilaterale" , explanation: "Il contributo a un ente bilaterale (EBT) è una quota, solitamente in percentuale sulla paga base e contingenza di ogni dipendente, destinata a finanziare le attività dell'ente. Questa quota è divisa tra azienda (datore di lavoro) e lavoratore, in percentuale diversa in base al settore e all'ente bilaterale."},
  { term: "imponibile fiscale" , explanation: "si definisce imponibile fiscale la parte del reddito su cui devono essere pagate le imposte. E' imponibile fiscale il reddito di lavoro dipendente percepito dal dipendente in ciascun periodo di paga e costituito da tutti i compensi in denaro o in natura che concorrono a formarlo."},
  { term: "irpef lorda" , explanation: "L'imposta lorda rappresenta l'importo complessivo che si ottiene applicando le aliquote previste dalla legge ai diversi scaglioni di reddito imponibile, ai fini dell'Irpef o di altre imposte progressive."},
  { term: "detrazioni detr. lav. dipendente" , explanation: "Le detrazioni da lavoro dipendente sono agevolazioni fiscali che permettono di ridurre l'IRPEF (Imposta sul Reddito delle Persone Fisiche) dovuta dai lavoratori con reddito da lavoro subordinato o assimilato."},
  { term: "detrazioni detr. coniuge" , explanation: "In particolare, le detrazioni per familiari a carico rappresentano delle somme che, in funzione della composizione del nucleo familiare e del reddito complessivo del lavoratore, si sottraggono, in misura progressiva, dall'imposta lorda, determinando l'imposta netta. n sostanza, è prevista una detrazione (800 euro per i redditi fino a 15.000 euro, 690 euro per i redditi fino a 40.000 euro) sulla base della quale calcolare l'importo effettivo, il quale diminuisce all'aumentare del reddito."},
  { term: "detrazioni detr. figli" , explanation: " Questo tipo di agevolazioni non sono nient'altro che degli sgravi fiscali che vengono concessi dal governo ai genitori che contano almeno un figlio a carico."},
  { term: "detrazioni detr. altri familiari" , explanation: "La formula per il calcolo è la seguente: 750 × [(80.000 - reddito complessivo) ÷ 80.000]. I familiari per cui possono spettare le agevolazioni sono genitori e, in loro mancanza, ascendenti più prossimi; fratelli e sorelle; suoceri, nuore, generi; adottanti."},
  { term: "detrazioni detr. oneri" , explanation: "Gli oneri deducibili sono quei costi che possono essere sottratti direttamente dal reddito complessivo del contribuente prima del calcolo dell'imposta. Ciò significa che tali spese riducono l'ammontare del reddito imponibile, abbassando di conseguenza l'importo dell'imposta dovuta."},
  { term: "imposta" , explanation: "Un'imposta è un tributo, ovvero un prelievo coattivo di ricchezza effettuato dallo Stato per sostenere la spesa pubblica. Le imposte si differenziano dalle tasse in quanto non corrispondono ad una prestazione ma sono un'entrata del bilancio statale. Le imposte si dividono in due categorie: dirette e indirette."},
  { term: "irpef netta" , explanation: "Sottraendo dalla retribuzione lorda (totale competenze) i contributi previdenziali, si ottiene l'imponibile Irpef. L'Irpef netta dovuta dal contribuente è determinata sottraendo dall'imposta lorda le detrazioni previste dalla normativa."},
  { term: "imponibile imp. impon. netto" , explanation: "L'imponibile netto in busta paga rappresenta la somma sulla quale vengono calcolate le imposte e le trattenute, dopo aver sottratto i contributi previdenziali e le deduzioni fiscali dalla retribuzione lorda"},
  { term: "imponibile imp. impon. lordo" , explanation: "L'imponibile lordo nella busta paga è l'importo totale di tutti gli emolumenti percepiti dal lavoratore, prima delle trattenute (contributi previdenziali, tasse, ecc.). È la base su cui vengono calcolate le imposte e i contributi dovuti. "},
  { term: "totale competenze" , explanation: "Il totale competenze in busta paga rappresenta la somma di tutti gli emolumenti dovuti al dipendente per la sua prestazione lavorativa, inclusi la retribuzione ordinaria, gli straordinari, i permessi, le vacanze, la malattia e la tredicesima e quattordicesima. Questo importo viene indicato come \"totale competenze\" nella busta paga e serve per calcolare la retribuzione lorda annuale (RAL)"},
  { term: "totale trattenute" , explanation: "Il totale delle trattenute nella busta paga rappresenta la somma di diverse voci che riducono lo stipendio lordo per ottenere lo stipendio netto. Queste includono contributi previdenziali, IRPEF (imposta sul reddito delle persone fisiche), addizionali regionali e comunali, e altri contributi come quelli per l'assistenza sanitaria o sindacale. "},
  { term: "totale detrazioni" , explanation: "Le detrazioni fiscali sono gli importi che il contribuente ha il diritto di sottrarre all'imposta lorda (totale delle tasse sui redditi di cui si è debitori verso lo stato) per stabilire l'imposta netta dovuta. "},
  { term: "imposta trattenuta" , explanation: "L'imposta trattenuta sulla busta paga è principalmente l'IRPEF, l'imposta sul reddito delle persone fisiche, che viene calcolata in base a fasce di reddito con aliquote crescenti. In aggiunta, vengono trattenuti i contributi previdenziali (INPS) e le addizionali regionali e comunali IRPEF. "},
  { term: "imposta conguaglio" , explanation: "Il conguaglio IRPEF è una rettifica eseguita dal datore di lavoro, solitamente nell'ultima busta paga dell'anno, per allineare le ritenute IRPEF effettivamente trattenute durante l'anno con l'importo che deve essere versato, basato sul reddito del dipendente risultante nella busta paga. "},
  { term: "quatita' quantità voce" , explanation: "In una busta paga, la sezione \"voce\" indica il tipo di retribuzione o trattenuta, mentre la sezione \"quantità\" indica l'ammontare in euro. Questa sezione specifica quanto viene pagato o trattenuto per ciascuna voce. "},
  { term: "voce" , explanation: "Il totale delle trattenute nella busta paga rappresenta la somma di diverse voci che riducono lo stipendio lordo per ottenere lo stipendio netto. Queste includono contributi previdenziali, IRPEF (imposta sul reddito delle persone fisiche), addizionali regionali e comunali, e altri contributi come quelli per l'assistenza sanitaria o sindacale. "},
  { term: "totale trattenute" , explanation: "Il totale delle trattenute nella busta paga rappresenta la somma di diverse voci che riducono lo stipendio lordo per ottenere lo stipendio netto. Queste includono contributi previdenziali, IRPEF (imposta sul reddito delle persone fisiche), addizionali regionali e comunali, e altri contributi come quelli per l'assistenza sanitaria o sindacale. "},
  { term: "retribuzione netta netto in busta", explanation: "La retribuzione netta in busta paga è l'importo effettivamente pagato al lavoratore dopo le trattenute per imposte, contributi previdenziali e altre deduzioni. È la somma che il lavoratore vede accreditata sul suo conto corrente. \nElaborazione:\nLa retribuzione netta si ottiene sottraendo dalla retribuzione lorda (l'ammontare totale della paga prima delle deduzioni) tutti gli oneri sociali e le trattenute fiscali a carico del dipendente. \nComponenti della retribuzione netta:\n\nStipendio lordo: l'importo totale della paga prima delle deduzioni.\n\nTrattenute:\n\nContributi previdenziali: quote versate all'INPS per la pensione.\n\nIRPEF (Imposta sul Reddito delle Persone Fisiche): l'imposta sul reddito.\nAddizionali regionali e comunali: tasse aggiuntive imposte dalle regioni e dai comuni. \nAltre trattenute: possono includere trattenute sindacali, anticipi su prestiti aziendali, ecc. \n\nRetribuzione netta: l'importo effettivamente pagato al lavoratore dopo le trattenute" },
  { term: "codice ditta azienda", explanation: "Il \"codice ditta\" o codice azienda in busta paga è un codice numerico, solitamente composto da 10 cifre, che identifica l'azienda datrice di lavoro. Questo codice, assegnato dall'INPS, è riportato nella busta paga, in particolare nella sezione \"Posizione INPS Azienda\" o simili. " },
  { term: "posizione pos. inail", explanation: "La posizione INAIL in busta paga è il numero identificativo che l'azienda utilizza per essere identificata presso l'Istituto Nazionale per l'Assicurazione contro gli Infortuni sul Lavoro. Questo numero si trova solitamente nella parte alta della busta paga, insieme ai dati aziendali (nome, indirizzo, codice fiscale). " },
  { term: "posizione pos. inps", explanation: "La posizione INPS in una busta paga si riferisce alla matricola INPS del datore di lavoro, che è un codice univoco che identifica l'azienda ai fini della gestione previdenziale. Puoi trovarla nell'intestazione della busta paga, insieme ad altri dati relativi all'azienda." },
  { term: "mese retribuzione", explanation: "Indica il mese a cui si riferisce la retribuzione in busta. La retribuzione mensile è calcolata per il periodo di un mese solare, indipendentemente dal numero di giorni lavorativi." },
  { term: "codice cod. dip.", explanation: "In una busta paga, \"cod. dip.\" si riferisce al codice dipendente, un identificativo numerico o alfanumerico assegnato al lavoratore per distinguere un dipendente dall'altro all'interno dell'azienda. Questo codice serve per la gestione della contabilità, delle pratiche INPS e altri scopi amministrativi legati al rapporto di lavoro. " },
  { term: "cognome e nome", explanation: "Dati anagrafici del dipendente." },
  { term: "codice cod. fiscale", explanation: "Codice fiscale del dipendente." },
  { term: "indirizzo", explanation: "Dove risiede il dipendente." },
  { term: "centro di costo", explanation: "Un centro di costo in azienda è una sezione, divisione o funzione interna che genera costi, spesso senza produrre direttamente ricavi. Questi centri di costo sono fondamentali per la gestione contabile e la valutazione dell'efficienza delle risorse aziendali. Sono utilizzati per raggruppare i costi relativi a un determinato reparto, prodotto, attività o progetto, consentendo di analizzare la redditività di ciascuna area.Il centro di costo può essere utilizzato per imputare i costi del personale a specifiche aree aziendali. Ad esempio, se un dipendente lavora in un determinato reparto, il suo stipendio e altri costi relativi (come la retribuzione aggiuntiva, i contributi previdenziali, ecc.) possono essere imputati al centro di costo di quel reparto. Questo permette di monitorare i costi totali di ciascuna area, inclusi quelli del personale, e di valutare l'efficienza e la redditività di ogni reparto o funzione. " },
  { term: "sede di lavoro", explanation: "La sede di lavoro è solitamente indicata nella busta paga, nella sezione dedicata ai dati del dipendente. In questa sezione, si trova il nome dell'azienda e l'indirizzo del luogo in cui si svolge l'attività lavorativa. " },
  { term: "assunzione", explanation: "La data di assunzione è un dato importante presente sulla busta paga, generalmente riportato nella parte superiore, insieme a altre informazioni sul lavoratore e sul contratto di lavoro." },
  { term: "convenzionale anz. conv.", explanation: "Indica la data di assunzione convenzionale, ovvero la data in cui il lavoratore viene considerato \"anziano\" nel contesto dell'azienda, anche se la data di assunzione legale è successiva. Questa data viene utilizzata per calcolare l'anzianità di servizio, che può influenzare lo stipendio o altri benefit." },
  { term: "anzianità anz. servizio", explanation: "L'anzianità di servizio, nella busta paga, rappresenta un aumento retributivo legato al tempo di servizio presso un'azienda. È un elemento che viene indicato come voce specifica nella busta paga, tra le componenti della retribuzione.Lo scatto di anzianità è una voce autonoma nella busta paga, indicando l'aumento retributivo legato al tempo di lavoro presso un'azienda. \nCalcolo:\n\nIl valore dello scatto di anzianità viene calcolato in base a diverse variabili, tra cui il contratto collettivo nazionale di lavoro (CCNL) di riferimento e il livello di inquadramento del lavoratore. \nFunzione:\nL'anzianità di servizio riflette l'idea che con il passare del tempo, un dipendente acquisisca maggiore esperienza e competenza, giustificando un aumento della retribuzione. " },
  { term: "scadenze contr.", explanation: "Le scadenze riguardanti il versamento della busta paga sono principalmente determinate dal contratto collettivo nazionale di lavoro (CCNL) che regola la tua attività. In generale, la busta paga deve essere pagata entro il 27 del mese o entro il 5 del mese successivo a quello a cui si riferisce la retribuzione." },
  { term: "fine rapporto", explanation: "Al termine del rapporto di lavoro, l'ultima busta paga comprende diverse competenze di fine rapporto, oltre alla retribuzione mensile regolare. Queste includono il TFR (Trattamento di Fine Rapporto), le ferie maturate non godute, e altre somme previste dal contratto collettivo nazionale di lavoro (CCNL). " },
  { term: "t.f.r. tfr", explanation: "TFR (Trattamento di Fine Rapporto):\nIl TFR è una somma di denaro maturata durante il rapporto di lavoro e corrisposta al dipendente all'atto della cessazione del lavoro. Il suo calcolo è basato sulla retribuzione annua lorda del dipendente, divisa per 13,5, poi moltiplicata per gli anni di servizio. " },
  { term: "qualifica", explanation: "La qualifica in busta paga rappresenta la classificazione professionale del lavoratore, indicata nel contratto collettivo e definita in base alle competenze e ai compiti svolti. In pratica, indica il livello professionale attribuito al lavoratore, che influenza la retribuzione e altri aspetti contrattuali. \nDove trovare la qualifica in busta paga:\n\nSolitamente, la qualifica è indicata nella sezione dedicata ai dati retributivi, accanto al livello contrattuale.\nPuò essere anche indicata nella sezione dedicata ai dati del dipendente o inquadramento contrattuale.\nPotresti trovare informazioni come il CCNL applicato, il livello di inquadramento e la mansione svolta. " },
  { term: "livello", explanation: "Il \"livello\" in busta paga indica la posizione gerarchica del dipendente all'interno dell'azienda, in base al Contratto Collettivo Nazionale di Lavoro (CCNL) applicato. Questo livello determina la retribuzione minima prevista per quella posizione e può influenzare anche la progressione di carriera. " },
  { term: "elemento elem. retr.", explanation: "\"Elem retr.\" in una busta paga si riferisce all'Elemento Distinto della Retribuzione (EDR), che è una voce retributiva fissa e continuativa, indipendente dal tipo di contratto del lavoratore (part-time, full-time, indeterminato, a termine, ecc.). L'EDR è una somma lorda, assoggetta a contribuzione e tassazione, come parte della retribuzione lorda complessiva. " },
  { term: "minimo", explanation: "Il salario minimo in Italia non è stabilito da una legge nazionale, ma è determinato dai contratti collettivi nazionali di lavoro (CCNL). La retribuzione minima, spesso indicata come paga base o minimo tabellare, varia in base al settore di appartenenza, al livello di inquadramento e alla qualifica del lavoratore. In alcuni casi, la legge prevede una soglia minima inderogabile, come la proposta di 9 euro l'ora, ma ciò non sostituisce il ruolo centrale del CCNL. " },
  { term: "aumento aum. per anz. anizanità", explanation: "Gli scatti di anzianità sono incrementi salariali previsti dai contratti collettivi nazionali di lavoro (CCNL) e riconosciuti ai dipendenti in base agli anni di servizio maturati presso la stessa azienda. Questi scatti, solitamente, sono una percentuale della paga minima contrattuale, spesso il 4%, e vengono aggiunti allo stipendio base. " },
  { term: "superminimo", explanation: "Il superminimo in busta paga è un compenso aggiuntivo alla retribuzione minima prevista dal CCNL (Contratto Collettivo Nazionale del Lavoro). Può essere riconosciuto per diverse ragioni, come il merito del dipendente, la sua funzione aziendale o le esigenze della stessa. Esistono due tipi di superminimo: quello assorbibile, che si riduce o si azzera con gli aumenti contrattuali, e quello non assorbibile, che rimane costante. " },
  { term: "ferie", explanation: "Le informazioni sulle ferie sono riportate in ogni busta paga, solitamente nella sezione bassa del cedolino, vicino ai contatori degli altri permessi retribuiti. Si trovano indicazioni sulle ferie maturate, quelle godute e quelle residue. \nDove trovarle:\n\nFerie maturate:\nSono le ferie accumulate dal lavoratore nel corso dell'anno in corso, generalmente indicate in giorni o ore.\n\n\nFerie godute:\nSono le ferie che il lavoratore ha già usufruito nel periodo di riferimento della busta paga. \n\n\nFerie residue:\nSono le ferie non ancora usufruite, calcolate sommando le ferie maturate dell'anno in corso e le ferie residue dell'anno precedente, al netto delle ferie già godute. \nCome leggerle:\n\nLe ferie possono essere indicate sia in ore che in giorni. Se indicate in giorni, per calcolare l'equivalente in ore, si moltiplica per 8 (o per il numero di ore lavorative giornaliere previste dal contratto). \nLe ferie residue (o non godute) rappresentano le ore o i giorni di ferie ancora disponibili al lavoratore. " },
  { term: "permessi riduzione orario r.o.l.", explanation: "I permessi per riduzione dell'orario di lavoro (ROL) vengono indicati nella busta paga e rappresentano una forma di permesso retribuito che consente di ridurre temporaneamente le ore di lavoro, spesso per esigenze personali o familiari. Questi permessi, generalmente previsti dai contratti collettivi, possono essere fruiti senza perdita di retribuzione. " },
  { term: "residuo res. anni precedenti", explanation: "Il residuo anni precedenti in busta paga indica le ferie non godute (o i permessi ROL) maturate nell'anno precedente e ancora disponibili da utilizzare nell'anno corrente. Si tratta di un diritto del lavoratore di usufruire di un numero di giorni di ferie o permessi che non sono stati utilizzati nell'anno in cui sono maturati. " },
  { term: "maturati", explanation: "In una busta paga, maturati si riferisce ai permessi, ferie o ROL (Riduzione Orologiale) che il lavoratore ha acquisito da inizio anno fino al mese corrente. In altre parole, sono le ore o i giorni di permesso che possono essere utilizzati come ferie retribuite. " },
  { term: "goduti", explanation: "In una busta paga, la sezione goduti si riferisce ai permessi, ferie o ROL che il dipendente ha utilizzato nel periodo di riferimento. Questa voce indica quanti giorni o ore di permesso sono stati effettivamente usufruiti dal dipendente. " },
  { term: "residui totali", explanation: "In una busta paga, i residui totali si riferiscono alla somma delle ore o dei giorni di ferie o di permessi che il lavoratore non ha ancora utilizzato e che gli spettano. Questi possono essere ROL (Riduzioni Orarie Lavorative), ferie o permessi di diversa natura, e vengono indicati in una sezione specifica della busta paga. " },
  { term: "modalità mod. pagamento", explanation: "La busta paga può essere pagata in vari modi tracciabili, come bonifico bancario, accredito su carta prepagata, assegno bancario o circolare, o pagamento diretto in banca o ufficio postale. È importante notare che il pagamento in contanti è vietato dal 1° luglio 2018. \nModalità di pagamento tracciabili:\n\nBonifico bancario:\nQuesta è la modalità più comune, dove il datore di lavoro accredita lo stipendio direttamente sul conto corrente del dipendente. \n\nAccredito su carta prepagata:\nSe il dipendente non possiede un conto corrente, è possibile utilizzare una carta prepagata per ricevere lo stipendio. \n\nAssegno bancario o circolare:\nIl datore di lavoro può consegnare un assegno al dipendente, che può essere incassato presso una banca.\n\nPagamento diretto in banca o ufficio postale:\nIl datore di lavoro può aprire un conto corrente di tesoreria e pagare lo stipendio direttamente al dipendente in contanti presso lo sportello, ma questa modalità è consentita solo per i conti di tesoreria con mandato di pagamento. " },
  { term: "riferimenti rif. bancari", explanation: "I riferimenti bancari nella busta paga, ovvero l'IBAN, sono le informazioni necessarie per effettuare l'accredito dello stipendio sul conto corrente del dipendente. Questo dato, insieme ad altre informazioni come l'ABI e il CAB (in caso di pagamenti tramite assegno), permette al datore di lavoro di effettuare il pagamento in modo corretto. \nRiferimenti bancari nella busta paga: cosa includono\n\nIBAN (International Bank Account Number): Questo è il codice bancario internazionale del conto corrente sul quale il dipendente desidera ricevere lo stipendio. \nABI (Codice ABI): Codice che identifica la banca. \nCAB (Codice CAB): Codice che identifica la filiale bancaria. \nEventuale indicazione della modalità di pagamento: La busta paga può indicare se il pagamento avviene tramite bonifico bancario, assegno o altra modalità. " },
  { term: "settimane sett. retr.", explanation: "Le settimane retribuite in busta paga si riferiscono al numero di settimane di ferie che un dipendente ha diritto a percepire come retribuzione, oltre a quelle effettivamente lavorate. In Italia, la legge garantisce un minimo di quattro settimane di ferie retribuite all'anno, secondo il decreto legislativo n. 66 dell'8 aprile 2003. " },
  { term: "giorni gg retr.", explanation: "I giorni retribuiti nella busta paga, spesso indicati come \"gg retribuiti\" o \"giorni retribuiti\", rappresentano il numero di giornate lavorative per cui il dipendente riceve la paga. Sono calcolati convenzionalmente considerando 26 giorni lavorativi per mese, anche se il numero effettivo di giorni lavorati potrebbe essere diverso. Questi giorni retribuiti includono anche i giorni festivi retribuiti. " },
  { term: "giorni gg lavorati", explanation: "Nella busta paga, la sezione dei \"giorni lavorati\" indica il numero di giorni per i quali il dipendente ha ricevuto la retribuzione. Questo valore può essere diverso dal numero di giorni effettivamente lavorati a causa di convenzioni contrattuali. " },
  { term: "ore lavorate", explanation: "Le ore lavorate sono quelle effettivamente svolte dal dipendente durante il periodo retributivo, escluse le assenze retribuite o non retribuite. La busta paga riporta le ore lavorate per calcolare la retribuzione lorda. " },
  { term: "retribuzione oraria", explanation: "La retribuzione oraria è il costo di una singola ora di lavoro, spesso calcolata dividendo lo stipendio mensile per il numero di ore lavorative mensili. In Italia, il salario orario medio nel settore privato è di circa 11,75 euro. " },
  { term: "retribuzione giornaliera", explanation: "La retribuzione giornaliera in busta paga si calcola dividendo la retribuzione mensile lorda per il numero di giorni lavorativi previsti nel mese, solitamente 26. Questa cifra rappresenta il valore giornaliero della tua retribuzione e viene utilizzata per calcolare la paga in caso di assenze o altre situazioni che richiedono una valutazione su base giornaliera. " },
  { term: "retribuzione mensile", explanation: "La retribuzione mensile, mostrata nella busta paga, è la somma di denaro che un dipendente percepisce mensilmente per il lavoro svolto. Comprende la retribuzione base, aumenti di merito, e altre voci ricorrenti come scatti di anzianità. La busta paga, o cedolino paga, è un documento ufficiale che il datore di lavoro è obbligato a consegnare al dipendente ogni mese, secondo la legge n. 300. \nElementi che compongono la retribuzione mensile:\n\nStipendio base (o retribuzione minima):\nÈ la somma di denaro che il dipendente percepisce in base al suo livello di inquadramento e al contratto collettivo nazionale di lavoro (CCNL) applicato. \n\nAumenti di merito:\nIn alcuni casi, il dipendente può ottenere un aumento di stipendio per il suo lavoro. \n\nScatti di anzianità:\nSi tratta di aumenti di stipendio che vengono concessi dopo un certo periodo di servizio presso l'azienda.\n\nAltre voci ricorrenti:\nPossono includere elementi come l'indennità di anzianità, assegni familiari, o altri bonus previsti dal CCNL. " },
  { term: "descrizione", explanation: "Descrizione a parole della voce associata" },
  { term: "unità unita' di misura", explanation: "Unità di misura della voce in ogetto solitamente ORE o GIORNI." },
  { term: "base", explanation: "La paga base in busta paga è lo stipendio minimo garantito, stabilito dai contratti collettivi nazionali di lavoro (CCNL) in base alla categoria professionale e al livello del lavoratore. Rappresenta l'elemento fondamentale e fisso della retribuzione, e può essere indicata come \"Paga base\" o \"Minimo tabellare/sindacale/contrattuale\". " },
  { term: "imponibile contributivo contr. arrot. arrotondato", explanation: "L'imponibile contributivo in busta paga è l'importo su cui si calcolano i contributi previdenziali (IVS) a carico del lavoratore e del datore di lavoro. In sostanza, è la base su cui vengono applicate le percentuali contributive per finanziare la pensione. " },
  { term: "retribuzione utile tfr", explanation: "La retribuzione utile TFR è la somma di tutti gli elementi retributivi che vengono presi in considerazione per calcolare il trattamento di fine rapporto (TFR). È una base di calcolo fondamentale per determinare la quota di TFR che matura mese per mese. \nIn dettaglio:\n\nCosa comprende:\nLa retribuzione utile TFR comprende tutte le voci della busta paga che sono correlate al rapporto di lavoro e che non sono di carattere occasionale o di rimborso spese. \nEsempi:\nTra queste voci, solitamente, rientrano:\n\nStipendio base\n\nContributi di legge\nTredicesima e quattordicesima (se previste)\nScatti di anzianità \nSuperminimi " },
  { term: "contributi contr. aggiuntivi agg. tfr", explanation: "Il contributo aggiuntivo TFR è un'eventuale somma, prevista da alcuni contratti collettivi, che il datore di lavoro versa in aggiunta al TFR maturato, destinandola ad un fondo pensione del dipendente. Non compare direttamente in busta paga come voce separata, ma può influire sul calcolo totale del TFR. " },
  { term: "ANF a.n.f. tabella compon. figli minori liv. livello reddito assegno", explanation: "L'Assegno al Nucleo Familiare (ANF) è una prestazione economica erogata dall'INPS ai nuclei familiari di alcuni lavoratori dipendenti. Per i lavoratori dipendenti, l'ANF viene corrisposto in busta paga dal datore di lavoro, che poi recupera l'importo con la compensazione dei contributi previdenziali dovuti all'INPS. " },
  { term: "totale spettante", explanation: "Il totale spettante in busta paga, comunemente chiamato \"importo netto\", è la somma che il lavoratore effettivamente riceve dopo che sono state effettuate tutte le ritenute fiscali e previdenziali. Questo importo è la cifra che viene versata sul conto corrente del lavoratore. " },
  { term: "totale contributi aliq. aliquota", explanation: "In una busta paga, la sezione \"contributi\" indica le trattenute per i contributi previdenziali (come l'INPS) e i contributi assistenziali (come l'Inail). Questi contribuiscono a finanziare il sistema pensionistico e la copertura per gli infortuni sul lavoro. La percentuale dei contributi varia in base al tipo di lavoratore e al suo reddito imponibile. " },
  { term: "inail", explanation: "In una busta paga, le voci legate all'INAIL (Istituto Nazionale per l'Assicurazione contro gli Infortuni sul Lavoro) riguardano principalmente il contributo INAIL, che è una parte della retribuzione complessiva del lavoratore e che il datore di lavoro versa ogni mese per garantire la copertura assicurativa contro infortuni sul lavoro e malattie professionali. " },
  { term: "importo", explanation: "L'importo busta paga (cedolino paga) è la somma di denaro che un lavoratore riceve come retribuzione per il lavoro svolto in un dato periodo, generalmente un mese. Questo importo è il frutto di diverse voci che, sottraendo le trattenute previdenziali e fiscali (IRPEF), danno origine al netto della busta paga. " },
  { term: "imposta sostituitiva", explanation: "L'imposta sostitutiva nella misura del 5% si applica però solo in presenza di determinati requisiti soggettivi. Quali sono? Anche per l'anno 2024, l'aliquota dell'imposta sostitutiva sui premi di produttività sarà confermata al 5%. E' quanto previsto nella legge di Bilancio 2024." },
  { term: "irpef imp sost", explanation: "Acronimo di imposta sul reddito delle persone fisiche, significa che tutti coloro che hanno un reddito, sia come lavoratore dipendente, sia come autonomo, nonché soci di impresa, sono tenuti a pagare questa imposta." },
  { term: "imposta conguaglio", explanation: "Il conguaglio IRPEF è una rettifica eseguita dal datore di lavoro, solitamente nell'ultima busta paga dell'anno, per allineare le ritenute IRPEF effettivamente trattenute durante l'anno con l'importo che deve essere versato, basato sul reddito del dipendente risultante nella busta paga." },
  { term: "riduzione tfr", explanation: "La riduzione del TFR sulla busta paga per i dipendenti pubblici, pari al 2,5% calcolato sull'80% della retribuzione, è stata abolita. In precedenza, questa trattenuta era destinata al versamento di contributi previdenziali soppressi. Questa riduzione non è una riduzione del TFR stesso, ma una trattenuta sulla busta paga per finanziare la previdenza. " },
  { term: "%", explanation: "Percentuale" },
  { term: "arrotondamento arr. precedente", explanation: "Arr. precedente in una busta paga di solito si riferisce a un importo che è stato arrotondato per difetto nel mese precedente e che viene poi recuperato nel mese corrente. Questo è spesso dovuto a calcoli che coinvolgono le aliquote fiscali o contributi previdenziali. L'arrotondamento precedente indica un importo che è stato precedentemente sottraito dalla busta paga per essere poi recuperato nel mese successivo, in modo da compensare l'arrotondamento effettuato in precedenza. " },
  { term: "arrotondamento arr. attuale", explanation: "L'acronimo \"arr. attuale\" nella busta paga potrebbe riferirsi a diverse voci, come ad esempio l'imposta di reddito delle persone fisiche (IRPEF), i contributi previdenziali, o l'avviso di ricezione del versamento di un importo specifico. Per capire esattamente a cosa si riferisce, è necessario consultare la sezione specifica della busta paga in cui appare questo acronimo. "},

]

// Configurazione di Fuse.js
const fuseOptions = {
  keys: ['term'],
  threshold: 0.4, // più basso = più preciso, più alto = più permissivo
}

const fuse = new Fuse(glossary, fuseOptions)

export async function GET(req: NextRequest) {
  try {
    const q = req.nextUrl.searchParams.get('q')

    if (!q) {
      return NextResponse.json({ error: 'Nessun testo ricevuto' }, { status: 400 })
    }

    const results = fuse.search(q)

    if (results.length > 0) {
      // Prendo il primo risultato migliore
      const bestMatch = results[0].item
      return NextResponse.json({ text: bestMatch.explanation })
    }

    return NextResponse.json({ text: "Nessuna spiegazione disponibile per questo termine." })
  } catch (err) {
    console.error('Errore imprevisto:', err)
    return NextResponse.json({ error: 'Errore interno del server' }, { status: 500 })
  }
}
